Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -30,7 +30,8 @@ jobs:
 
     - name: Delete existing EC2 key pair if present
       run: |
-        aws ec2 delete-key-pair --key-name loki-prod-key || echo "Key not found, skipping delete"
+        aws ec2 delete-key-pair --key-name loki-prod-key --region ap-south-1 || echo "Key not found, skipping delete"
+
 
     - name: Terraform Plan
       run: terraform plan -out=tfplan
