Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -28,6 +28,10 @@ jobs:
     - name: Terraform Init
       run: terraform init
 
+    - name: Delete existing EC2 key pair if present
+      run: |
+        aws ec2 delete-key-pair --key-name loki-prod-key || echo "Key not found, skipping delete"
+
     - name: Terraform Plan
       run: terraform plan -out=tfplan
 
